//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("cat.md ver:0.9.31204.3")]
[assembly: System.Reflection.AssemblyDescription("cat.md")]
[assembly: System.Reflection.AssemblyProduct("cat.md")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) 2009-2013 Kody Brown.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("9FB08B1A-5CCD-4695-9FD6-627C1F0F4457")]
[assembly: System.Reflection.AssemblyVersion("0.9.31204.3")]
[assembly: System.Reflection.AssemblyFileVersion("0.9.31204.3")]


